# every time a PR is opened, add missing translations

name: Translation Sync

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      - name: Scan
        run: |
          curl https://openrouter.ai/api/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer "$OPENROUTER_API_KEY" \
            -d '{
            "model": "openai/gpt-oss-120b",
            "messages": [
              {
                "role": "user",
                "content": "What's the weather in Kyoto?"
              }
            ],
            "reasoning": {
              "enabled": true
            }
          }
